// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"
#include "frc/Joystick.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class Drivetrain: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
std::shared_ptr<WPI_TalonSRX> frontLeft;
std::shared_ptr<WPI_TalonSRX> backLeft;
std::shared_ptr<WPI_TalonSRX> frontRight;
std::shared_ptr<WPI_TalonSRX> backRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
Drivetrain();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	void userDrive(std::shared_ptr<frc::Joystick>mainController); //Method to drive robot using joystick input.
	void encoderPosition(double left, double right); //Method to move robot a distance using encoders.
	void encoderDone();
	void encoderReset();
	bool isMove(); //Determines whether the robot is moving.
	double ftToRotations(double ft); //Method to convert from feet to rotations. The talons only work in rotations.


	static const int kTimeoutMs = 10; //Talon timeout default

	static const int kSensorUnitsPerRotation = 360; // E4T encoder

	static constexpr double kGearRatio = 10.71; //Mini box motor gear ratio

	static constexpr double kWheelDiam = (6.0/12); //Diameter of the wheel in feet

	double l_pos;
	double r_pos;

	double slowFactor = 0.6;


};
