// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ConveyorBack.h"
#include "Commands/ConveyorForward.h"
#include "Commands/ConveyorStop.h"
#include "Commands/ISolenoidIn.h"
#include "Commands/ISolenoidOut.h"
#include "Commands/IntakeIn.h"
#include "Commands/IntakeOut.h"
#include "Commands/IntakeStop.h"
#include "Commands/Shoot.h"
#include "Commands/ShooterStop.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
mainController.reset(new frc::Joystick(0));

rBump.reset(new frc::JoystickButton(mainController.get(), 6));
rBump->WhileHeld(new ISolenoidIn());
lBump.reset(new frc::JoystickButton(mainController.get(), 5));
lBump->WhileHeld(new ISolenoidOut());
y.reset(new frc::JoystickButton(mainController.get(), 4));
y->WhileHeld(new ConveyorBack());
x.reset(new frc::JoystickButton(mainController.get(), 3));
x->WhileHeld(new ConveyorForward());
b.reset(new frc::JoystickButton(mainController.get(), 2));
b->WhileHeld(new IntakeOut());
a.reset(new frc::JoystickButton(mainController.get(), 1));
a->WhileHeld(new IntakeIn());

    // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getMainController() {
   return mainController;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
