// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/LimelightTrack.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LimelightTrack::LimelightTrack(): frc::Command() {
    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::vision.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    Requires(Robot::drivetrain.get());

frc::SmartDashboard::PutNumber("Steering KP", 0.055);
frc::SmartDashboard::PutNumber("min TA", 2.1);
frc::SmartDashboard::PutNumber("Driving KP", 0.80);

}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void LimelightTrack::Initialize() {

m_steeringKP = frc::SmartDashboard::GetNumber("Steering KP", 0.0);
m_targetArea = frc::SmartDashboard::GetNumber("min TA", 0.0);
m_driveKP = frc::SmartDashboard::GetNumber("Driving KP", 0.0);

frc::SmartDashboard::PutNumber("Left", 10000);
frc::SmartDashboard::PutNumber("Right", 10000);

}

// Called repeatedly when this Command is scheduled to run
void LimelightTrack::Execute() {

double right = Robot::vision->getTx()*m_steeringKP; // Right Y
double left  = (m_targetArea-Robot::vision->getTa())*m_driveKP; // Left X
frc::SmartDashboard::PutNumber("target area", Robot::vision->getTa());
frc::SmartDashboard::PutNumber("Left", left);
frc::SmartDashboard::PutNumber("Right", right);
    if (Robot::vision->getTv()) {
      if (Robot::vision->getTa() >= m_targetArea) {
        left = 0;
        right = 0;
      }
    } else {
     left = 0;
     right = 0;
    }

    Robot::drivetrain->autoDrive(left, right);
  }

// Make this return true when this Command no longer needs to run execute()
bool LimelightTrack::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void LimelightTrack::End() {
    Robot::drivetrain->autoDrive(0.0, 0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LimelightTrack::Interrupted() {
    End();
}
