// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Conveyor.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Conveyor::Conveyor() : frc::Subsystem("Conveyor") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
leftConveyorMotor.reset(new WPI_TalonSRX(7));


rightConveyorMotor.reset(new WPI_TalonSRX(8));



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    leftConveyorMotor->ConfigSelectedFeedbackSensor(FeedbackDevice::IntegratedSensor);
    rightConveyorMotor->Follow(*leftConveyorMotor);

    leftConveyorMotor->SetNeutralMode(NeutralMode::Brake);
    rightConveyorMotor->SetNeutralMode(NeutralMode::Brake);

    leftConveyorMotor->Config_kF(0, kF, mTimeout);
    leftConveyorMotor->Config_kP(0, kP, mTimeout);
    leftConveyorMotor->Config_kI(0, kI, mTimeout);
    leftConveyorMotor->Config_kD(0, kD, mTimeout);

}

void Conveyor::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Conveyor::Periodic() {
    // Put code here to be run every loop

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Conveyor::ConveyorRun()
{
    leftConveyorMotor->Set(ControlMode::Velocity, conveyorSpeed);
}

void Conveyor::ConveyorStop()
{
    leftConveyorMotor->Set(ControlMode::PercentOutput, 0.0);
    
}
