// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutoShooter.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ClimbPull.h"
#include "Commands/ClimberPistonIn.h"
#include "Commands/ClimberPistonOut.h"
#include "Commands/ClimberWiinchReverse.h"
#include "Commands/ClimberWinchRun.h"
#include "Commands/ClimberWinchStop.h"
#include "Commands/ConveyorOff.h"
#include "Commands/ConveyorRun.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/EncoderDrive.h"
#include "Commands/IntakeDown.h"
#include "Commands/IntakeDownSequence.h"
#include "Commands/IntakeRun.h"
#include "Commands/IntakeStop.h"
#include "Commands/IntakeUp.h"
#include "Commands/IntakeUpSequence.h"
#include "Commands/LimelightOff.h"
#include "Commands/LimelightTrack.h"
#include "Commands/ManualClimber.h"
#include "Commands/ManualIntake.h"
#include "Commands/ManualShooter.h"
#include "Commands/ShootSequence.h"
#include "Commands/SpinnerPositionControl.h"
#include "Commands/SpinnerRotationControl.h"
#include "Commands/StopShooter.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
systemsController.reset(new frc::Joystick(1));

sc_X.reset(new frc::JoystickButton(systemsController.get(), 3));
sc_X->WhenPressed(new SpinnerRotationControl());
sc_Y.reset(new frc::JoystickButton(systemsController.get(), 4));
sc_Y->WhenPressed(new SpinnerPositionControl());
sc_Rbump.reset(new frc::JoystickButton(systemsController.get(), 6));
sc_Rbump->WhileHeld(new ClimberWinchRun());
sc_Lbump.reset(new frc::JoystickButton(systemsController.get(), 5));
sc_Lbump->WhenPressed(new ClimberPistonOut());
sc_B.reset(new frc::JoystickButton(systemsController.get(), 2));
sc_B->WhileHeld(new ShootSequence());
sc_A.reset(new frc::JoystickButton(systemsController.get(), 1));
sc_A->WhileHeld(new IntakeDownSequence());
driveController.reset(new frc::Joystick(0));

mc_Rbump.reset(new frc::JoystickButton(driveController.get(), 6));
mc_Rbump->WhileHeld(new LimelightTrack());
mc_B.reset(new frc::JoystickButton(driveController.get(), 2));
mc_B->WhenPressed(new EncoderDrive(0, 0));

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("IntakeRun", new IntakeRun());
    frc::SmartDashboard::PutData("LimelightOff", new LimelightOff());
    frc::SmartDashboard::PutData("ManualClimber", new ManualClimber());
    frc::SmartDashboard::PutData("ManualIntake", new ManualIntake());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getDriveController() {
   return driveController;
}

std::shared_ptr<frc::Joystick> OI::getSystemsController() {
   return systemsController;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
